### ISSUE TITLE
Files for Predictive Analytics in KNIME - Machine Learning AI to Predict Customer Churn

### ISSUE THREAD

**Issue by jhagege** [PacktPublishing/KNIME-A-Guide-for-Absolute-Beginners#1]
Hi the files for the last chapter Predictive Analytics in KNIME - Machine Learning AI to Predict Customer Churn are not available.
Can you please upload them? Thanks, great course!

**Comment by Sonakshis** [comment]
Hi 

Thank you for bringing this to our attention. We have updated the code bundle.

https://github.com/PacktPublishing/KNIME-A-Guide-for-Absolute-Beginners/blob/78eaeb137d06fda562337e5b01ed87805ebda2fd/Predictive%20Analytics%20Customers.xlsx 

https://github.com/PacktPublishing/KNIME-A-Guide-for-Absolute-Beginners/blob/main/New%20Customer%20Prediction.xlsx
